### ISSUE TITLE
Call to undefined function get_site_meta()

### ISSUE THREAD

**Issue by phluid61** [wp-cli/entity-command#235]
```
$ wp site meta get 123 foo
Fatal error: Uncaught Error: Call to undefined function get_site_meta() in phar:///usr/local/bin/wp/vendor/wp-cli/entity-command/src/Site_Meta_Command.php:89
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/entity-command/src/WP_CLI/CommandWithMeta.php(151): Site_Meta_Command->get_metadata('123', 'foo', true)
#1 [internal function]: WP_CLI\CommandWithMeta->get(Array, Array)
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(93): call_user_func(Array, Array, Array)
#3 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(449): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(366): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(389): WP_CLI\Runner->run_command(Array, Array)
#7 phar:///usr/local/bin/wp/ve in phar:///usr/local/bin/wp/vendor/wp-cli/entity-command/src/Site_Meta_Command.php on line 89
```

WordPress 5.0.3

```
$ wp --version
WP-CLI 2.1.0
$ php --version
PHP 7.3.2-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 15:43:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

Happens when site `123` exists, irrespective of what meta field I pass in.

**Comment by swissspidy** [comment]
What WordPress version are you using? Are you running Multisite? `get_site_meta` is new since WordPress 5.1 and is a Multisite function.

**Comment by schlessera** [comment]
So it is expected that `site meta` does not work on your version of WordPress ( 5.0.3), it requires WordPress 5.1+.

However, it should tell you so instead of throwing a fatal error. It looks like the logic is off here:

https://github.com/wp-cli/entity-command/blob/943fd52c6afb31fbf59206e40db93350cac7cf3c/entity-command.php#L35

This should actually be:
```
if ( ! function_exists( 'is_site_meta_supported' ) || ! is_site_meta_supported() ) {
```
